import { defineField, defineType } from "sanity";

export const chalet = defineType({
  name: "chalet",
  title: "Chalet",
  type: "document",
  fields: [
    defineField({
      name: "name",
      title: "Name",
      type: "string",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      options: { source: "name" },
      validation: (r) => r.required(),
    }),
    defineField({
      name: "destination",
      title: "Destination",
      type: "reference",
      to: [{ type: "destination" }],
    }),
    defineField({
      name: "bedrooms",
      title: "Bedrooms",
      type: "number",
    }),
    defineField({
      name: "sleeps",
      title: "Sleeps",
      type: "number",
    }),
    defineField({
      name: "priceOnRequest",
      title: "Price on Request",
      type: "boolean",
      description: "When enabled, displays 'Price on request' instead of the price range.",
      initialValue: false,
    }),
    defineField({
      name: "priceRange",
      title: "Price Range",
      type: "object",
      hidden: ({ document }) => !!document?.priceOnRequest,
      fields: [
        defineField({ name: "min", title: "Minimum", type: "number" }),
        defineField({ name: "max", title: "Maximum", type: "number" }),
        defineField({
          name: "currency",
          title: "Currency",
          type: "string",
          initialValue: "GBP",
        }),
      ],
    }),
    defineField({
      name: "amenities",
      title: "Amenities",
      type: "array",
      of: [{ type: "string" }],
      options: { layout: "tags" },
      description: "e.g. Hot tub, Sauna, Ski room, Private chef",
    }),
    defineField({
      name: "includedServices",
      title: "Included Services",
      type: "array",
      of: [{ type: "string" }],
      options: { layout: "tags" },
      description: "Services included in the rental — e.g. Daily housekeeping, Airport transfer, Ski guiding",
    }),
    defineField({
      name: "onRequest",
      title: "On Request",
      type: "array",
      of: [{ type: "string" }],
      options: { layout: "tags" },
      description: "Services available on request — e.g. Private chef, Helicopter transfer, Massage therapist",
    }),
    defineField({
      name: "location",
      title: "Location",
      type: "geopoint",
      description: "On Google Maps: right-click the property location → click the coordinates that appear.",
    }),
    defineField({
      name: "gallery",
      title: "Gallery",
      type: "array",
      of: [{ type: "image", options: { hotspot: true } }],
      options: { layout: "grid" },
      description: "Select multiple images at once by holding Cmd (Mac) or Ctrl (Windows) in the file picker.",
    }),
    defineField({
      name: "description",
      title: "Description",
      type: "array",
      of: [{ type: "block" }],
    }),
  ],
});
