import { defineField, defineType } from "sanity";
import { GalleryInput } from "../components/GalleryInput";

export const destination = defineType({
  name: "destination",
  title: "Destination",
  type: "document",
  fields: [
    // ── Core ─────────────────────────────────────────────────────────────────
    defineField({
      name: "name",
      title: "Name",
      type: "string",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      options: { source: "name" },
      validation: (r) => r.required(),
    }),
    defineField({
      name: "region",
      title: "Region",
      type: "string",
      description: 'e.g. "The Alps", "British Columbia", "Antarctica"',
    }),

    // ── SEO ──────────────────────────────────────────────────────────────────
    defineField({
      name: "seoTitle",
      title: "SEO Title",
      type: "string",
      description: "Page title for search engines. Max 60 characters. Generated by Content Tools.",
      validation: (r) => r.max(60),
    }),
    defineField({
      name: "metaDescription",
      title: "SEO Meta Description",
      type: "string",
      description: "Max 155 characters. Used by search engines and social sharing. Generated by Content Tools.",
      validation: (r) => r.max(155),
    }),

    // ── Short copy ────────────────────────────────────────────────────────────
    defineField({
      name: "tagline",
      title: "Tagline",
      type: "string",
      description: "Short hero tagline — 6–10 words, no full stop. Generated by Content Tools.",
    }),
    defineField({
      name: "shortDescription",
      title: "Short Description",
      type: "text",
      rows: 2,
      description: "~25 words used on listing cards and hub pages. Generated by Content Tools.",
    }),

    // ── Editorial ─────────────────────────────────────────────────────────────
    defineField({
      name: "editorialIntro",
      title: "Editorial Intro",
      type: "text",
      rows: 8,
      description: "150–200 word editorial introduction establishing the destination's character. Generated by Content Tools.",
    }),

    // ── Area Guide ────────────────────────────────────────────────────────────
    defineField({
      name: "areaGuide",
      title: "Area Guide",
      type: "object",
      description: "Structured guide sections shown on the destination page. Generated by Content Tools.",
      fields: [
        defineField({
          name: "terrainAndSkiing",
          title: "Terrain & Skiing",
          type: "text",
          rows: 4,
        }),
        defineField({
          name: "villageCharacter",
          title: "Village Character",
          type: "text",
          rows: 4,
        }),
        defineField({
          name: "gettingThere",
          title: "Getting There",
          type: "text",
          rows: 4,
        }),
        defineField({
          name: "bestFor",
          title: "Best For",
          type: "text",
          rows: 3,
        }),
      ],
    }),

    // ── The Edit Picks ────────────────────────────────────────────────────────
    defineField({
      name: "theEditPicks",
      title: "The Edit Picks",
      type: "array",
      description: "3 curated recommendations — link to Expeditions or Chalets collections. Generated by Content Tools.",
      of: [
        {
          type: "object",
          fields: [
            defineField({
              name: "name",
              title: "Name",
              type: "string",
              validation: (r) => r.required(),
            }),
            defineField({
              name: "category",
              title: "Category",
              type: "string",
              options: {
                list: ["Expedition", "Chalet", "Lodge", "Heli-Ski", "Experience"],
              },
              validation: (r) => r.required(),
            }),
            defineField({
              name: "description",
              title: "One-line description",
              type: "string",
              validation: (r) => r.required(),
            }),
            defineField({
              name: "link",
              title: "Link URL (relative)",
              type: "string",
              description: 'e.g. "/expeditions/verbier-haute-route"',
            }),
          ],
          preview: { select: { title: "name", subtitle: "category" } },
        },
      ],
      validation: (r) => r.max(3),
    }),

    // ── FAQs ──────────────────────────────────────────────────────────────────
    defineField({
      name: "faqs",
      title: "FAQs",
      type: "array",
      description: "6 questions targeting real search queries about this destination. Generated by Content Tools.",
      of: [
        {
          type: "object",
          fields: [
            defineField({
              name: "question",
              title: "Question",
              type: "string",
              validation: (r) => r.required(),
            }),
            defineField({
              name: "answer",
              title: "Answer",
              type: "text",
              rows: 3,
              validation: (r) => r.required(),
            }),
          ],
          preview: { select: { title: "question" } },
        },
      ],
      validation: (r) => r.max(6),
    }),

    // ── Related Destinations ──────────────────────────────────────────────────
    defineField({
      name: "relatedDestinations",
      title: "Related Destinations",
      type: "array",
      description: "3 suggested related destinations with rationale. Generated by Content Tools.",
      of: [
        {
          type: "object",
          fields: [
            defineField({
              name: "destination",
              title: "Destination",
              type: "reference",
              to: [{ type: "destination" }],
            }),
            defineField({
              name: "rationale",
              title: "Rationale",
              type: "string",
              description: "Why this destination is suggested — shown internally only.",
            }),
          ],
          preview: { select: { title: "destination.name", subtitle: "rationale" } },
        },
      ],
      validation: (r) => r.max(3),
    }),

    // ── Media ─────────────────────────────────────────────────────────────────
    defineField({
      name: "heroImage",
      title: "Hero Image",
      type: "image",
      options: { hotspot: true },
    }),
    defineField({
      name: "gallery",
      title: "Gallery",
      type: "array",
      of: [{ type: "image", options: { hotspot: true } }],
      options: { layout: "grid" },
      components: { input: GalleryInput },
      description: "Use 'Add multiple images from library' to select many at once. Drag to reorder.",
    }),

    // ── Legacy ────────────────────────────────────────────────────────────────
    defineField({
      name: "intro",
      title: "Intro (legacy)",
      type: "text",
      rows: 3,
      description: "Superseded by Short Description above. Kept for backwards compatibility.",
    }),
    defineField({
      name: "description",
      title: "Description (legacy)",
      type: "array",
      of: [{ type: "block" }],
      description: "Superseded by Editorial Intro above. Kept for backwards compatibility.",
    }),
  ],
});
