import { defineField, defineType } from "sanity";
import { GalleryInput } from "../components/GalleryInput";

export const lodge = defineType({
  name: "lodge",
  title: "Lodge",
  type: "document",
  fields: [
    // ── Core ─────────────────────────────────────────────────────────────────
    defineField({
      name: "name",
      title: "Name",
      type: "string",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      options: { source: "name" },
      validation: (r) => r.required(),
    }),
    defineField({
      name: "destination",
      title: "Destination",
      type: "reference",
      to: [{ type: "destination" }],
    }),

    // ── SEO ──────────────────────────────────────────────────────────────────
    defineField({
      name: "seoTitle",
      title: "SEO Title",
      type: "string",
      description: "Page title for search engines. Max 60 characters. Generated by Content Tools.",
      validation: (r) => r.max(60),
    }),
    defineField({
      name: "metaDescription",
      title: "SEO Meta Description",
      type: "string",
      description: "Max 155 characters. Used by search engines and social sharing. Generated by Content Tools.",
      validation: (r) => r.max(155),
    }),

    // ── Short copy ────────────────────────────────────────────────────────────
    defineField({
      name: "tagline",
      title: "Tagline",
      type: "string",
      description: "Short hero tagline — 6–10 words, no full stop. Generated by Content Tools.",
    }),
    defineField({
      name: "shortDescription",
      title: "Short Description",
      type: "text",
      rows: 2,
      description: "~25 words used on listing cards. Generated by Content Tools.",
    }),

    // ── Editorial ─────────────────────────────────────────────────────────────
    defineField({
      name: "editorialIntro",
      title: "Editorial Intro",
      type: "text",
      rows: 8,
      description: "150–200 words written to create desire for somewhere unfamiliar. Generated by Content Tools.",
    }),

    // ── Lodge guide sections ──────────────────────────────────────────────────
    defineField({
      name: "accessAndLogistics",
      title: "Access & Logistics",
      type: "text",
      rows: 4,
      description: "How to get there, transfer options, access conditions. Generated by Content Tools.",
    }),
    defineField({
      name: "seasonWindow",
      title: "Season Window & What to Expect",
      type: "text",
      rows: 4,
      description: "Best months to visit, weather, snow conditions, what the experience feels like. Generated by Content Tools.",
    }),
    defineField({
      name: "terrain",
      title: "Terrain",
      type: "text",
      rows: 4,
      description: "Character of the surrounding landscape and skiing/adventure terrain. Generated by Content Tools.",
    }),
    defineField({
      name: "physicalRequirements",
      title: "Physical Requirements",
      type: "object",
      description: "Honest assessment of fitness level required. Generated by Content Tools.",
      fields: [
        defineField({
          name: "level",
          title: "Level",
          type: "string",
          options: {
            list: [
              { title: "None — suitable for all abilities", value: "None" },
              { title: "Moderate — reasonable fitness required", value: "Moderate" },
              { title: "Demanding — strong fitness and experience required", value: "Demanding" },
            ],
            layout: "radio",
          },
        }),
        defineField({
          name: "descriptor",
          title: "Descriptor",
          type: "text",
          rows: 2,
          description: "Honest one or two sentence description of what is required.",
        }),
      ],
    }),

    // ── Signature Experiences ─────────────────────────────────────────────────
    defineField({
      name: "signatureExperiences",
      title: "Signature Experiences",
      type: "array",
      description: "3 standout experiences linking to the Expeditions collection. Generated by Content Tools.",
      of: [
        {
          type: "object",
          fields: [
            defineField({
              name: "name",
              title: "Name",
              type: "string",
              validation: (r) => r.required(),
            }),
            defineField({
              name: "description",
              title: "One-line description",
              type: "string",
              validation: (r) => r.required(),
            }),
            defineField({
              name: "link",
              title: "Link URL (relative)",
              type: "string",
              description: 'e.g. "/expeditions/alta-via-ski-traverse"',
            }),
          ],
          preview: { select: { title: "name", subtitle: "description" } },
        },
      ],
      validation: (r) => r.max(3),
    }),

    // ── FAQs ──────────────────────────────────────────────────────────────────
    defineField({
      name: "faqs",
      title: "FAQs",
      type: "array",
      description: "6 questions targeting experiential and logistical long-tail search queries. Generated by Content Tools.",
      of: [
        {
          type: "object",
          fields: [
            defineField({
              name: "question",
              title: "Question",
              type: "string",
              validation: (r) => r.required(),
            }),
            defineField({
              name: "answer",
              title: "Answer",
              type: "text",
              rows: 3,
              validation: (r) => r.required(),
            }),
          ],
          preview: { select: { title: "question" } },
        },
      ],
      validation: (r) => r.max(6),
    }),

    // ── Property details ──────────────────────────────────────────────────────
    defineField({
      name: "bedrooms",
      title: "Bedrooms",
      type: "number",
    }),
    defineField({
      name: "sleeps",
      title: "Sleeps",
      type: "number",
    }),
    defineField({
      name: "priceOnRequest",
      title: "Price on Request",
      type: "boolean",
      description: "When enabled, displays 'Price on request' instead of the price range.",
      initialValue: false,
    }),
    defineField({
      name: "priceRange",
      title: "Price Range",
      type: "object",
      hidden: ({ document }) => !!document?.priceOnRequest,
      fields: [
        defineField({ name: "min", title: "Minimum", type: "number" }),
        defineField({ name: "max", title: "Maximum", type: "number" }),
        defineField({ name: "currency", title: "Currency", type: "string", initialValue: "GBP" }),
      ],
    }),
    defineField({
      name: "style",
      title: "Style",
      type: "string",
      description: 'e.g. "Backcountry cabin", "Alpine chalet", "Tented camp"',
    }),
    defineField({
      name: "amenities",
      title: "Amenities",
      type: "array",
      of: [{ type: "string" }],
      options: { layout: "tags" },
      description: "e.g. Hot tub, Sauna, Ski room, Private chef",
    }),
    defineField({
      name: "includedServices",
      title: "Included Services",
      type: "array",
      of: [{ type: "string" }],
      options: { layout: "tags" },
      description: "Services included in the rental — e.g. Daily housekeeping, Airport transfer, Ski guiding",
    }),
    defineField({
      name: "onRequest",
      title: "On Request",
      type: "array",
      of: [{ type: "string" }],
      options: { layout: "tags" },
      description: "Services available on request — e.g. Private chef, Helicopter transfer, Massage therapist",
    }),

    // ── Media & location ──────────────────────────────────────────────────────
    defineField({
      name: "location",
      title: "Location",
      type: "geopoint",
      description: "On Google Maps: right-click the property location → click the coordinates that appear.",
    }),
    defineField({
      name: "altitude",
      title: "Altitude (metres)",
      type: "number",
      description: "Resort or property altitude in metres above sea level — e.g. 1800",
    }),
    defineField({
      name: "gallery",
      title: "Gallery",
      type: "array",
      of: [{ type: "image", options: { hotspot: true } }],
      options: { layout: "grid" },
      components: { input: GalleryInput },
      description: "Use 'Add multiple images from library' to select many at once. Drag to reorder.",
    }),

    // ── Legacy ────────────────────────────────────────────────────────────────
    defineField({
      name: "description",
      title: "Description (legacy)",
      type: "array",
      of: [{ type: "block" }],
      description: "Superseded by Editorial Intro above. Kept for backwards compatibility.",
    }),
  ],
});
